alarm/devtools-alarm to 1.4.0-3
closes #1969

diff --git a/alarm/devtools-alarm/0001-makechrootpkg-cache-dir.patch b/alarm/devtools-alarm/0001-makechrootpkg-cache-dir.patch
--- a/alarm/devtools-alarm/0001-makechrootpkg-cache-dir.patch
+++ b/alarm/devtools-alarm/0001-makechrootpkg-cache-dir.patch
@@ -1,40 +1,42 @@
-From d7db6adbb1f9b58e86148117d5449c18232c8a43 Mon Sep 17 00:00:00 2001
+From b3b18976a7b68572ea831018d8bdb4b857d62938 Mon Sep 17 00:00:00 2001
 From: Kevin Mihelich <kevin@archlinuxarm.org>
 Date: Sun, 28 Dec 2014 22:25:58 -0700
-Subject: [PATCH 1/9] makechrootpkg: cache dir
+Subject: [PATCH 1/8] makechrootpkg: cache dir
 
 ---
- makechrootpkg.in | 10 ++++++++--
+ src/makechrootpkg.in | 10 ++++++++--
  1 file changed, 8 insertions(+), 2 deletions(-)
 
-diff --git a/makechrootpkg.in b/makechrootpkg.in
-index 126d1da..aef2702 100644
---- a/makechrootpkg.in
-+++ b/makechrootpkg.in
-@@ -56,6 +56,7 @@ usage() {
- 	echo 'Flags:'
- 	echo '-h         This help'
- 	echo '-c         Clean the chroot before building'
-+	echo '-X <dir>   Set pacman cache to pass to arch-nspawn'
- 	echo '-d <dir>   Bind directory into build chroot as read-write'
- 	echo '-D <dir>   Bind directory into build chroot as read-only'
- 	echo '-u         Update the working copy of the chroot before building'
-@@ -274,12 +275,13 @@ move_products() {
+diff --git a/src/makechrootpkg.in b/src/makechrootpkg.in
+index e7cbc9c..4458e3a 100644
+--- a/src/makechrootpkg.in
++++ b/src/makechrootpkg.in
+@@ -84,6 +84,7 @@ usage() {
+ 	echo '-T                Build in a temporary directory'
+ 	echo '-U                Run makepkg as a specified user'
+ 	echo '-x <when>         Inspect chroot after build (never, always, failure)'
++	echo '-X <dir>          Set pacman cache to pass to arch-nspawn'
+ 	exit 1
+ }
+ 
+@@ -293,7 +294,7 @@ move_products() {
  }
  # }}}
  
--while getopts 'hcur:I:l:nCTD:d:U:' arg; do
-+while getopts 'hcuX:r:I:l:nCTD:d:U:' arg; do
+-while getopts 'hcur:I:l:nCTD:d:U:x:t:' arg; do
++while getopts 'hcuX:r:I:l:nCTD:d:U:x:t:' arg; do
  	case "$arg" in
  		c) clean_first=1 ;;
  		D) bindmounts_ro+=("--bind-ro=$OPTARG") ;;
- 		d) bindmounts_rw+=("--bind=$OPTARG") ;;
- 		u) update_first=1 ;;
+@@ -308,6 +309,7 @@ while getopts 'hcur:I:l:nCTD:d:U:x:t:' arg; do
+ 		T) temp_chroot=1; copy+="-$$" ;;
+ 		U) makepkg_user="$OPTARG" ;;
+ 		x) inspect="$OPTARG" ;;
 +		X) cache_dir="$OPTARG" ;;
- 		r) passeddir="$OPTARG" ;;
- 		I) install_pkgs+=("$OPTARG") ;;
- 		l) copy="$OPTARG" ;;
-@@ -302,6 +304,10 @@ chrootdir=$(readlink -e "$passeddir")
+ 		h|*) usage ;;
+ 	esac
+ done
+@@ -323,6 +325,10 @@ chrootdir=$(readlink -e "$passeddir")
  [[ ! -d $chrootdir ]] && die "No chroot dir defined, or invalid path '%s'" "$passeddir"
  [[ ! -d $chrootdir/root ]] && die "Missing chroot dir root directory. Try using: mkarchroot %s/root base-devel" "$chrootdir"
  
@@ -45,15 +47,15 @@ index 126d1da..aef2702 100644
  if [[ ${copy:0:1} = / ]]; then
  	copydir=$copy
  else
-@@ -361,7 +367,7 @@ download_sources
- 
- prepare_chroot
+@@ -396,7 +402,7 @@ nspawn_build_args=(
+ 	"${bindmounts_tmpfs[@]}"
+ )
  
 -if arch-nspawn "$copydir" \
 +if arch-nspawn $cache_dir "$copydir" \
- 	--bind="${PWD//:/\\:}:/startdir" \
- 	--bind="${SRCDEST//:/\\:}:/srcdest" \
- 	"${bindmounts_ro[@]}" "${bindmounts_rw[@]}" \
+ 	"${nspawn_build_args[@]}" \
+ 	/chrootbuild "${makepkg_args[@]}"
+ then
 -- 
-2.36.1
+2.51.2
 
