extra/postgresql to 18.0-1

diff --git a/extra/postgresql/PKGBUILD b/extra/postgresql/PKGBUILD
--- a/extra/postgresql/PKGBUILD
+++ b/extra/postgresql/PKGBUILD
@@ -1,60 +1,62 @@
+# Maintainer: Jan Alexander Steffens (heftig) <heftig@archlinux.org>
 # Maintainer: Levente Polyak <anthraxx[at]archlinux[dot]org>
-# Maintainer: Dan McGee <dan@archlinux.org>
+# Contributor: Dan McGee <dan@archlinux.org>
 
 # ALARM: Kevin Mihelich <kevin@archlinuxarm.org>
 #  - patch to fix AArch64 FTBFS with LLVM 21
 
 pkgbase=postgresql
 pkgname=(
-  'postgresql'
-  'postgresql-libs'
-  'postgresql-docs'
+  postgresql
+  postgresql-libs
+  postgresql-docs
 )
-pkgver=17.6
-_majorver=${pkgver%.*}
-pkgrel=2
-pkgdesc='Sophisticated object-relational DBMS'
-url='https://www.postgresql.org/'
-arch=('x86_64')
-license=('PostgreSQL')
+pkgver=18.0
+pkgrel=1
+pkgdesc="Sophisticated object-relational DBMS"
+url="https://www.postgresql.org/"
+arch=(x86_64)
+license=(PostgreSQL)
 depends=(
-  'bash'
-  'gcc-libs'
-  'glibc'
-  'icu'
-  'krb5'
-  'libldap'
-  'libxml2'
-  'libxslt'
-  'llvm-libs'
-  'lz4'
-  'openssl'
-  'pam'
-  'readline'
-  'systemd-libs'
-  'util-linux-libs'
-  'zlib'
-  'zstd'
+  bash
+  gcc-libs
+  glibc
+  icu
+  krb5
+  libldap
+  liburing
+  libxml2
+  libxslt
+  llvm-libs
+  lz4
+  numactl
+  openssl
+  pam
+  systemd-libs
+  util-linux-libs
+  zlib
+  zstd
 )
 makedepends=(
-  'clang'
-  'docbook-xml'
-  'docbook-xsl'
-  'llvm'
-  'perl'
-  'perl-ipc-run'
-  'python'
-  'systemd'
-  'tcl'
-  'util-linux'
+  clang
+  curl
+  docbook-xml
+  docbook-xsl
+  llvm
+  perl
+  perl-ipc-run
+  python
+  readline
+  systemd
+  tcl
+  util-linux
 )
 source=(
   https://ftp.postgresql.org/pub/source/v${pkgver}/postgresql-${pkgver}.tar.bz2
   0001-Set-DEFAULT_PGSOCKET_DIR-to-run-postgresql.patch
   0002-Force-RPATH-to-be-used-for-the-PL-Perl-plugin.patch
   0003-doc-Remove-stray-trailing-whitespace-in-xref-linkend.patch
-  0004-jit-fix-build-with-LLVM-21.patch
-  0005-llvm-21-aarch64.patch
+  0004-llvm-21-aarch64.patch
   postgresql-check-db-dir.in
   postgresql.logrotate
   postgresql.pam
@@ -62,35 +64,10 @@ source=(
   postgresql.sysusers
   postgresql.tmpfiles
 )
-md5sums=('e72b7e5dc22d44d56b113ed1f74e4084'
-         'a5b05db6d869c74a2fc0d8f752618b1d'
-         'b74d848f5527740dce663ae72f39c5ae'
-         'c26bfbec0b715eccfc67d9a42ef80669'
-         '0d34dd948e5b031d9ae4312a1eb10bd6'
-         '58fdb5a17290bde6f9d45c908ea00b38'
-         '10123caec61006cbe316de8ab7a497bc'
-         'd28e443f9f65a5712c52018b84e27137'
-         '96f82c38f3f540b53f3e5144900acf17'
-         'fe9d4dea2d878a7f0b555b0dae333793'
-         'da6a0dda84638d0c3463abf4bc01e621'
-         '9138244e0e6b98acc770931a4b150b86')
-sha256sums=('e0630a3600aea27511715563259ec2111cd5f4353a4b040e0be827f94cd7a8b0'
-            '2c09429dca9caf540be647fdac9540eeccb68935994bb54cfd3f2108464916c7'
-            '0fb4915c06b9767933b27adc329e7319485e043fb9f17b1697b969779a00cf14'
-            '4a9bb5c8c02b410646269276345073d478fe285996b1b1564cae5f59ad02a174'
-            'ee6a8220d846c3064ca93dbdc656a0ffbcfad8736333fae17b40e5e65d4ed558'
-            'b19e69d83736b3e0144d422df59f34505ce60ebb0e6bc429985e7fb11a40d67c'
-            '94af93b53bf7772e6664c239523ef952ffc905a0de3c2c4b2dfc2fe8f3a2efed'
-            '6abb842764bbed74ea4a269d24f1e73d1c0b1d8ecd6e2e6fb5fb10590298605e'
-            '57dfd072fd7ef0018c6b0a798367aac1abb5979060ff3f9df22d1048bb71c0d5'
-            '3a0bbf9fd61259c4898465c55a8b7cd26202885132ff2b5c685dfe0e0ddd4968'
-            '3cfe36dd202af56b3ef8e6d6a746b24e6f46f0d9e0d3fa125dbfb5e598170afb'
-            'ea771830c15b24c8725ded92e6a9ba9848b13f722357c5f5857dfeb21985d54c')
-b2sums=('9287eab85e17a65333d970bf7d4d254e25295615b4787072ff2a6c705cb66b7775dbe3a0c6b6fa3e2ab37c3278d204ccfdd3e587226d4c1d6363868569149216'
-        'c924fd8f58a85d0ed073af7f9778467db6d106b8b66e011048c5148a6b7d02afe4d02451970bd08d351a7356abe7b9a8ea17e3bf1cce32f17977196215d49b5b'
+b2sums=('3ef4759a0292d039e035ddbe20ec3eeb450a68c391363ca29af8c2e31b61a8e2dbd4ae6f37bf8c58e9b21ba0e182eda959d029bc5e061814e13259ab43ff1c1d'
+        '057e65b1e5a1fd82c7fa9da1c4e2fef39321ee59f74f54d9864e8ab4d7db4862c8fb6353f6006e1a9e1f5132543cf0c12b388963487a09b1465447b3ff6d7321'
         'd98280e004adcb1ad85053d9bd202a2b4798df6e7a72b21cb263da6b282f42b5463ce77dcc4f0b1b39d3f55303d0f6869b23f2338ffcd98720b0550204adf85a'
-        '7a296d7639c72964651973d0d38bc32c8f9c96c65ed8d8e98e520de04cf26c98c361b9567875fca6fc27191eb59709499800076e7bf1354ae6e51c444e7669eb'
-        '392403ece1c5886d6e0d7062091dc71ec1cb085d1da2e0d4b91638c875c5d84ce2b2e4faca05ee336f57a9482e81aeccf882c9ced8dd56091095f5f612d86e03'
+        '6546d3ea661c777b4f60587be1ec8ce4703dd6b56d308675330a72bc88c5ecff71fb29c7d371afa108b2c4d411f99b261bc92e72bf8fb5bfc015ee07d724b336'
         'd730f79f14ec6c0e4b3b8cbe7b885643de4830c6ce19c20d5e349e4009cf81b017168324595a4d72841f07da2fc8bbbcd2c3d310163f8e76358203d90f34ce99'
         '682bfab1189221d82f6cce9bcb8c40c6d37ecacbcaf0568bbaa2706503b1f102e5476d0d110dcc6240ab62c5e7c2c20a5d9af8edd4038d212327f8866b1cf15a'
         '2209b7550acad7955102ec6922754b4046b2a2ad2a7e1cfb2cc4053c0705abac7aa7d7968eab617f50894797d06345f51c9a669926bd2a77dcf688206a2027e0'
@@ -99,19 +76,39 @@ b2sums=('9287eab85e17a65333d970bf7d4d254e25295615b4787072ff2a6c705cb66b7775dbe3a
         'e025e78797879323bb78752dff8ea4eae984015240d273de8e83e1b7f7f7a8b9a549c33df6b72c40721f05a3df149fe065f9bb8c3fdf4f3b9f759963bb3da288'
         'd66fcad8c00ed29cb50cf6721c89023787b42973c3bf50535c4f822a8870883557396b3ec5cc79465e75d0786246a523db69368b2a7feff40c3430c736999cca')
 
-# Upstream provides md5 and sha256
+# PostgreSQL releases are unsigned and only provide these sums
+md5sums=('ce1c99eafd54278847a04c299cff80c5'
+         '344d51b4e3ddf4cb4c2e143650b0476b'
+         'b74d848f5527740dce663ae72f39c5ae'
+         'ccb488a57547b1ae1a2f93a828113859'
+         '58fdb5a17290bde6f9d45c908ea00b38'
+         '10123caec61006cbe316de8ab7a497bc'
+         'd28e443f9f65a5712c52018b84e27137'
+         '96f82c38f3f540b53f3e5144900acf17'
+         'fe9d4dea2d878a7f0b555b0dae333793'
+         'da6a0dda84638d0c3463abf4bc01e621'
+         '9138244e0e6b98acc770931a4b150b86')
+sha256sums=('0d5b903b1e5fe361bca7aa9507519933773eb34266b1357c4e7780fdee6d6078'
+            '064b7e266094e07feae29735efab3246e2b7a3364d6948d2f98d338e827d6a1a'
+            '0fb4915c06b9767933b27adc329e7319485e043fb9f17b1697b969779a00cf14'
+            '670a36a00d4dba7c6c5242dadc32ccef28a86a5064f814d95d9248d283f6c1d3'
+            'b19e69d83736b3e0144d422df59f34505ce60ebb0e6bc429985e7fb11a40d67c'
+            '94af93b53bf7772e6664c239523ef952ffc905a0de3c2c4b2dfc2fe8f3a2efed'
+            '6abb842764bbed74ea4a269d24f1e73d1c0b1d8ecd6e2e6fb5fb10590298605e'
+            '57dfd072fd7ef0018c6b0a798367aac1abb5979060ff3f9df22d1048bb71c0d5'
+            '3a0bbf9fd61259c4898465c55a8b7cd26202885132ff2b5c685dfe0e0ddd4968'
+            '3cfe36dd202af56b3ef8e6d6a746b24e6f46f0d9e0d3fa125dbfb5e598170afb'
+            'ea771830c15b24c8725ded92e6a9ba9848b13f722357c5f5857dfeb21985d54c')
 
 prepare() {
   cd postgresql-${pkgver}
   patch -Np1 < ../0001-Set-DEFAULT_PGSOCKET_DIR-to-run-postgresql.patch
   patch -Np1 < ../0002-Force-RPATH-to-be-used-for-the-PL-Perl-plugin.patch
   patch -Np1 < ../0003-doc-Remove-stray-trailing-whitespace-in-xref-linkend.patch
-  patch -Np1 < ../0004-jit-fix-build-with-LLVM-21.patch
-  patch -Np1 < ../0005-llvm-21-aarch64.patch
+  patch -Np1 < ../0004-llvm-21-aarch64.patch
 }
 
 build() {
-  cd postgresql-${pkgver}
   local configure_options=(
     --prefix=/usr
     --sysconfdir=/etc
@@ -123,6 +120,9 @@ build() {
     --with-gssapi
     --with-icu
     --with-ldap
+    --with-libcurl
+    --with-libnuma
+    --with-liburing
     --with-libxml
     --with-libxslt
     --with-llvm
@@ -139,34 +139,37 @@ build() {
     --with-zstd
   )
 
-  # Fix static libs
+  # use fat LTO objects for static libraries
   CFLAGS+=" -ffat-lto-objects"
+  CXXFLAGS+=" -ffat-lto-objects"
 
-  ./configure "${configure_options[@]}"
+  mkdir -p build; cd build
+  ../postgresql-${pkgver}/configure "${configure_options[@]}"
   make world
 }
 
-_postgres_check() {
-  make "${1}" || (find . -name regression.diffs | \
-    while read -r line; do
-      echo "make ${1} failure: ${line}"
-      cat "${line}"
-    done; exit 1)
-}
-
-check() {
+check() (
   export LANG=C LC_ALL=C
-  cd postgresql-${pkgver}
-  _postgres_check check
-  _postgres_check check-world
+  if ! make -C build check-world; then
+    find . -name regression.diffs | while read -r line; do
+      echo "make check-world failure: ${line}"
+      cat -- "${line}" || :
+    done
+    exit 1
+  fi
+)
+
+_pick() {
+  local p="$1" f d; shift
+  for f; do
+    d="${srcdir}/${p}/${f#${pkgdir}/}"
+    mkdir -p "$(dirname "${d}")"
+    mv "${f}" "${d}"
+    rmdir -p --ignore-fail-on-non-empty "$(dirname "${f}")"
+  done
 }
 
 package_postgresql() {
-  pkgdesc='Sophisticated object-relational DBMS'
-  backup=(
-    'etc/logrotate.d/postgresql'
-    'etc/pam.d/postgresql'
-  )
   depends+=("postgresql-libs>=${pkgver}")
   optdepends=(
     'logrotate: rotates system logs automatically'
@@ -175,121 +178,91 @@ package_postgresql() {
     'python: for PL/Python 3 support'
     'tcl: for PL/Tcl support'
   )
-  options+=('staticlibs')
+  options+=(staticlibs)
   install=postgresql.install
+  backup=(
+    etc/logrotate.d/postgresql
+    etc/pam.d/postgresql
+  )
 
-  cd postgresql-${pkgver}
+  make -C build DESTDIR="${pkgdir}" install-world
 
-  # install
-  make DESTDIR="${pkgdir}" install
-  make -C contrib DESTDIR="${pkgdir}" install
-  make -C doc/src/sgml DESTDIR="${pkgdir}" install-man
+  (
+    cd "${pkgdir}"
 
-  # we don't want these, they are in the -libs package
-  for dir in src/interfaces src/bin/pg_config src/bin/pg_dump src/bin/psql src/bin/scripts; do
-    make -C ${dir} DESTDIR="${pkgdir}" uninstall
-  done
-  for util in pg_config pg_dump pg_dumpall pg_restore psql \
-      clusterdb createdb createuser dropdb dropuser pg_isready reindexdb vacuumdb; do
-    rm "${pkgdir}"/usr/share/man/man1/${util}.1
-  done
+    _pick libs usr/bin/pg_{config,dump,dumpall,isready,restore}
+    _pick libs usr/bin/{cluster,reindex,vacuum}db
+    _pick libs usr/bin/{create,drop}{db,user}
+    _pick libs usr/bin/{ecpg,psql,vacuumlo}
 
-  # clean up unneeded installed items
-  rm -rf "${pkgdir}/usr/include/postgresql/internal"
-  rm -rf "${pkgdir}/usr/include/libpq"
-  find "${pkgdir}/usr/include" -maxdepth 1 -type f -execdir rm {} +
-  rmdir "${pkgdir}/usr/share/doc/postgresql/html"
+    _pick libs usr/include/{ecpg,libpq,pg,postgres_,sql}*
+    _pick libs usr/include/postgresql/internal
 
-  pushd "${srcdir}"
+    _pick libs usr/lib/lib*
+    _pick libs usr/lib/pkgconfig
 
-  sed -e "s/%PGMAJORVERSION%/${_majorver}/g" \
-      -e "s/%PREVMAJORVERSION%/$((_majorver - 1))/g" \
+    _pick libs usr/share/locale/*/LC_MESSAGES/{ecpg,libpq,pgscripts,psql}*
+    _pick libs usr/share/locale/*/LC_MESSAGES/pg_{config,dump}-*
+
+    _pick libs usr/share/man/man1/pg_{config,dump,dumpall,isready,restore}.1
+    _pick libs usr/share/man/man1/{cluster,reindex,vacuum}db.1
+    _pick libs usr/share/man/man1/{create,drop}{db,user}.1
+    _pick libs usr/share/man/man1/{ecpg,psql,vacuumlo}.1
+
+    _pick libs usr/share/postgresql/{pg_service.conf,psqlrc}.sample
+
+    _pick docs usr/share/doc
+  )
+
+  local majorver=${pkgver%%.*}
+  sed -e "s/%PGMAJORVERSION%/${majorver}/g" \
+      -e "s/%PREVMAJORVERSION%/$((majorver - 1))/g" \
       postgresql-check-db-dir.in |
-    install -Dm 755 /dev/stdin "${pkgdir}/usr/bin/postgresql-check-db-dir"
+    install -Dm755 /dev/stdin "${pkgdir}/usr/bin/postgresql-check-db-dir"
 
-  install -Dm 644 ${pkgname}.pam "${pkgdir}/etc/pam.d/${pkgname}"
-  install -Dm 644 ${pkgname}.logrotate "${pkgdir}/etc/logrotate.d/${pkgname}"
+  install -Dm644 postgresql.pam "${pkgdir}/etc/pam.d/postgresql"
+  install -Dm644 postgresql.logrotate "${pkgdir}/etc/logrotate.d/postgresql"
+  install -Dm644 postgresql.service -t "${pkgdir}/usr/lib/systemd/system"
+  install -Dm644 postgresql.sysusers "${pkgdir}/usr/lib/sysusers.d/postgresql.conf"
+  install -Dm644 postgresql.tmpfiles "${pkgdir}/usr/lib/tmpfiles.d/postgresql.conf"
 
-  install -Dm 644 ${pkgname}.service -t "${pkgdir}/usr/lib/systemd/system"
-  install -Dm 644 ${pkgname}.sysusers "${pkgdir}/usr/lib/sysusers.d/${pkgname}.conf"
-  install -Dm 644 ${pkgname}.tmpfiles "${pkgdir}/usr/lib/tmpfiles.d/${pkgname}.conf"
-
-  popd
-
-  install -Dm 644 COPYRIGHT -t "${pkgdir}/usr/share/licenses/${pkgname}"
+  install -Dm644 postgresql-${pkgver}/COPYRIGHT -t "${pkgdir}/usr/share/licenses/${pkgname}"
 }
 
 package_postgresql-libs() {
-  pkgdesc="Libraries for use with PostgreSQL"
+  pkgdesc+=" - Client binaries and libraries"
   depends=(
-    'glibc'
-    'krb5'
-    'libldap'
-    'lz4'
-    'openssl'
-    'readline'
-    'zlib'
-    'zstd'
+    curl libcurl.so
+    glibc
+    krb5 libgssapi_krb5.so
+    libldap
+    lz4 liblz4.so
+    openssl libcrypto.so libssl.so
+    readline libreadline.so
+    zlib libz.so
+    zstd libzstd.so
   )
   provides=(
-    'libecpg.so'
-    'libecpg_compat.so'
-    'libpgtypes.so'
-    'libpq.so'
-    'postgresql-client'
+    libecpg.so
+    libecpg_compat.so
+    libpgtypes.so
+    libpq.so
+    postgresql-client
   )
-  conflicts=('postgresql-client')
+  conflicts=(postgresql-client)
 
-  cd postgresql-${pkgver}
+  mv libs/* "${pkgdir}"
 
-  # install libs and non-server binaries
-  for dir in src/interfaces src/bin/pg_config src/bin/pg_dump src/bin/psql src/bin/scripts; do
-    make -C ${dir} DESTDIR="${pkgdir}" install
-  done
-
-  for util in pg_config pg_dump pg_dumpall pg_restore psql \
-      clusterdb createdb createuser dropdb dropuser pg_isready reindexdb vacuumdb; do
-    install -Dm 644 doc/src/sgml/man1/${util}.1 "${pkgdir}"/usr/share/man/man1/${util}.1
-  done
-
-  pushd src/include
-
-  install -d "${pkgdir}"/usr/include/{libpq,postgresql/internal/libpq}
-
-  # these headers are needed by the public headers of the interfaces
-  install -m 644 pg_config.h "${pkgdir}/usr/include"
-  install -m 644 pg_config_os.h "${pkgdir}/usr/include"
-  install -m 644 pg_config_ext.h "${pkgdir}/usr/include"
-  install -m 644 postgres_ext.h "${pkgdir}/usr/include"
-  install -m 644 libpq/libpq-fs.h "${pkgdir}/usr/include/libpq"
-  install -m 644 pg_config_manual.h "${pkgdir}/usr/include"
-
-  # these he aders are needed by the not-so-public headers of the interfaces
-  install -m 644 c.h "${pkgdir}/usr/include/postgresql/internal"
-  install -m 644 port.h "${pkgdir}/usr/include/postgresql/internal"
-  install -m 644 postgres_fe.h "${pkgdir}/usr/include/postgresql/internal"
-  install -m 644 libpq/pqcomm.h "${pkgdir}/usr/include/postgresql/internal/libpq"
-
-  popd
-
-  install -Dm 644 COPYRIGHT -t "${pkgdir}/usr/share/licenses/${pkgname}"
+  install -Dm644 postgresql-${pkgver}/COPYRIGHT -t "${pkgdir}/usr/share/licenses/${pkgname}"
 }
 
 package_postgresql-docs() {
-  pkgdesc="HTML documentation for PostgreSQL"
+  pkgdesc+=" - HTML documentation"
   depends=()
-  options+=('docs')
 
-  cd postgresql-${pkgver}
+  mv docs/* "${pkgdir}"
 
-  make -C doc/src/sgml DESTDIR="${pkgdir}" install-html
-  chown -R root:root "${pkgdir}/usr/share/doc/postgresql/html"
-
-  # clean up
-  rmdir "${pkgdir}"/usr/share/man/man{1,3,7}
-  rmdir "${pkgdir}"/usr/share/man
-
-  install -Dm 644 COPYRIGHT -t "${pkgdir}/usr/share/licenses/${pkgname}"
+  install -Dm644 postgresql-${pkgver}/COPYRIGHT -t "${pkgdir}/usr/share/licenses/${pkgname}"
 }
 
 # vim:set sw=2 sts=-1 et:
