extra/firefox to 55.0.1-1

diff --git a/extra/firefox/upload-symbol-archive b/extra/firefox/upload-symbol-archive
--- a/extra/firefox/upload-symbol-archive
+++ b/extra/firefox/upload-symbol-archive
@@ -5,10 +5,19 @@ die() {
   exit 1
 }
 
-(( $# == 2 )) || die "Usage: $0 TOKEN-FILE SYMBOL-ARCHIVE"
-[[ -f $1 && -s $1 ]] || die "Invalid TOKEN-FILE ${1@Q}"
-[[ $(file -Ebi "$2") == application/zip* ]] || die "Invalid SYMBOL-ARCHIVE ${2@Q}"
+(( $# >= 2 )) || die "Usage: $0 TOKEN-FILE SYMBOL-ARCHIVE..."
+token="$1"
+shift
 
-echo >&2 "Uploading ${2@Q} ..."
-exec curl -X POST -H "Auth-Token: $(<"$1")" -F "${2##*/}=@$2" \
-  https://crash-stats.mozilla.com/symbols/upload
+[[ -f $token && -s $token ]] || die "Invalid TOKEN-FILE ${token@Q}"
+
+for zip; do
+  [[ $(file -Ebi "$zip") == application/zip* ]] || die "Invalid SYMBOL-ARCHIVE ${zip@Q}"
+done
+
+for zip; do
+  echo >&2 "Uploading ${zip@Q} ..."
+  curl -X POST -H "Auth-Token: $(<"$token")" -F "${zip##*/}=@$zip" \
+    https://crash-stats.mozilla.com/symbols/upload
+  echo
+done
