core/linux-armv7: Add firmware failsafe check
A simple check at the end of the `package` function to exemplary check
one of the firmware files that are added with a patch. If that patch is
not applied correctly, that file is missing and the kernel build will
later fail. All this really does is catch an obvious error early.
The exit code was arbitrarily chosen just so it is unique.

diff --git a/core/linux-armv7/PKGBUILD b/core/linux-armv7/PKGBUILD
--- a/core/linux-armv7/PKGBUILD
+++ b/core/linux-armv7/PKGBUILD
@@ -78,6 +78,12 @@ prepare() {
   # don't run depmod on 'make install'. We'll do this ourselves in packaging
   sed -i '2iexit 0' scripts/depmod.sh
 
+  if [ ! -f "./firmware/regulatory.db" ];
+  then
+    echo "Missing regulatory.db firmware file, looks like the patches failed to apply correctly."
+    exit 101
+  fi
+
   unset GIT_CEILING_DIRECTORIES
 }
 
