Lots of weekend extra PKGBUILDs and core updates

diff --git a/util/archmobile b/util/archmobile
--- a/util/archmobile
+++ b/util/archmobile
@@ -10,7 +10,7 @@ HELP='n'
 BUILD='n'
 CHROOT='n'
 # ARCH can be specified on the command line. Otherwise we'll guess.
-ARCH='i686'
+ARCH='arm'
 # Which groups and additional packages are to install.
 TARGETS=()
 # PACMAN_EXTRA takes extra flags passed to pacman. No checking is done.
@@ -63,28 +63,28 @@ printHelp() {
 
 # Check if we are already able to interpret ARM binaries and configure the
 # the kernel if we are not. Expects mount call and echo call as arguments.
-binfmt_mount() {                                                        
-  MOUNT_CALL="$1"
-  ECHO_CALL="$2"
-
-  debug "Checking for binfmt_misc."                                             
-  if [ ! -e /proc/sys/fs/binfmt_misc/register ]; then
-    debug "binfmt_misc not mounted."
-
-    debug "$MOUNT_CALL -t binfmt_misc none /proc/sys/fs/binfmt_misc"
-    $MOUNT_CALL -t binfmt_misc none /proc/sys/fs/binfmt_misc &>/dev/null
-    test $? -ne 0 && \
-      error "Failed to mount binfmt_misc."
-  fi
-  if [ ! -f /proc/sys/fs/binfmt_misc/arm ]; then
-      debug "$ECHO_CALL ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-static-arm:' > /proc/sys/fs/binfmt_misc/register"
-      $ECHO_CALL ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-static-arm:' > /proc/sys/fs/binfmt_misc/register
-      test $? -ne 0 && \ 
-        error "Failed to write ARM binary information to binfmt_misc/register."
-
-      debug "binfmt_misc successfully created and configured."
-  fi
-}
+#binfmt_mount() {                                                        
+#  MOUNT_CALL="$1"
+#  ECHO_CALL="$2"
+#
+#  debug "Checking for binfmt_misc."                                             
+#  if [ ! -e /proc/sys/fs/binfmt_misc/register ]; then
+#    debug "binfmt_misc not mounted."
+#
+#    debug "$MOUNT_CALL -t binfmt_misc none /proc/sys/fs/binfmt_misc"
+#    $MOUNT_CALL -t binfmt_misc none /proc/sys/fs/binfmt_misc &>/dev/null
+#    test $? -ne 0 && \
+#      error "Failed to mount binfmt_misc."
+#  fi
+#  if [ ! -f /proc/sys/fs/binfmt_misc/arm ]; then
+#      debug "$ECHO_CALL ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-static-arm:' > /proc/sys/fs/binfmt_misc/register"
+#      $ECHO_CALL ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-static-arm:' > /proc/sys/fs/binfmt_misc/register
+#      test $? -ne 0 && \ 
+#        error "Failed to write ARM binary information to binfmt_misc/register."
+#
+#      debug "binfmt_misc successfully created and configured."
+#  fi
+#}
 
 debug() {
   test "$DEBUG" = "y" && echo "debug: $1"
@@ -282,7 +282,7 @@ test -z "${TARGETS[*]}" && TARGETS=(base kernel26)
 test -z "$ARCH" && ARCH="$(arch 2>/dev/null)"
 test -z "$ARCH" && \
   error "Could not obtain architecture type. Please use --arch manually."
-if [ "$ARCH" != 'i686' -a "$ARCH" != 'x86_64' ]; then
+if [ "$ARCH" != 'arm' -a "$ARCH" != 'armv5tel' ]; then
   error "Host system's architecture $ARCH is not supported"
 fi
 
@@ -426,4 +426,3 @@ doCleanup
 
 exit 0
 
-# vim: set ft=sh ts=2 sw=2 et:
