alarm/firmware-brcm43xx: Support for Wandboard
Instead of hard coding the TTY, guess it or use whatever is defined in the conf file.

diff --git a/alarm/firmware-brcm43xx/start-brcm-patchram-plus b/alarm/firmware-brcm43xx/start-brcm-patchram-plus
--- a/alarm/firmware-brcm43xx/start-brcm-patchram-plus
+++ b/alarm/firmware-brcm43xx/start-brcm-patchram-plus
@@ -37,9 +37,26 @@ if [ "$a" = "0x4330" ] ; then
   EXTRA="--no2bytes --enable_lpm --tosleep=50000 "
 fi
 
+# UART TTY can be different for each board
+# FIXME: Possibly test each port with hciattach (-n)?
+#        For now, just use the highest port as it works for current boards
+if [ -z "$TTY" ]; then
+	TTYS=($( ls -r1 /dev/ttymxc? ))
+	for t in "${TTYS[@]}" ; do
+		ttynum=${t:0-1}
+		if [ $ttynum -eq 0 ]; then
+			echo "Abort: UART ttymcx0 does not seem right."
+			exit 1
+		else
+			TTY=$t
+			break
+		fi
+	done
+fi
+
 if [ -n "$HCD" ] ; then
   echo "Found chip version $a."
-  /usr/bin/brcm_patchram_plus -d --patchram /usr/lib/firmware/brcm/$HCD --baudrate 3000000 --use_baudrate_for_download /dev/ttymxc3 --enable_hci $EXTRA $MAC_OPTIONS &
+  /usr/bin/brcm_patchram_plus -d --patchram /usr/lib/firmware/brcm/$HCD --baudrate 3000000 --use_baudrate_for_download ${TTY} --enable_hci $EXTRA $MAC_OPTIONS &
 else
   echo " No device Found."
   exit 1
