alarm/firmware-bcrm43xx: Missing conf.d file
* Install conf.d file with available variables
* New TTY and HCD conf.d vars

diff --git a/alarm/firmware-brcm43xx/start-brcm-patchram-plus b/alarm/firmware-brcm43xx/start-brcm-patchram-plus
--- a/alarm/firmware-brcm43xx/start-brcm-patchram-plus
+++ b/alarm/firmware-brcm43xx/start-brcm-patchram-plus
@@ -14,27 +14,25 @@ fi
 MAC_OPTIONS="--bd_addr $MAC_ADDR"
 
 # Find chip version
-DEVS=($( cat /sys/class/mmc_host/mmc?/mmc?\:0001/mmc?\:0001:?/device ))
-for DEV in "${DEVS[@]}"; do
-	if [ "${DEV:0:4}" = "0x43" ]; then
-		a="$DEV"
+if [ -z "$HCD" ]; then
+	DEVS=($( cat /sys/class/mmc_host/mmc?/mmc?\:0001/mmc?\:0001:?/device ))
+	for DEV in "${DEVS[@]}"; do
+		if [ "${DEV:0:4}" = "0x43" ]; then
+			a="$DEV"
+		fi
+	done
+	if [ -z "$a" ]; then
+		echo "Failed: Unable to locate bluetooth device"
+		exit 1
 	fi
-done
-if [ -z "$a" ]; then
-	echo "Failed: Unable to locate bluetooth device"
-	exit 1
-fi
 
-HCD=""
-EXTRA=""
-
-if [ "$a" = "0x4329" ] ; then
-  HCD="bcm4329.hcd"
-fi
+	if [ "$a" = "0x4329" ] ; then
+		HCD="bcm4329.hcd"
+	fi
  
-if [ "$a" = "0x4330" ] ; then
-  HCD="bcm4330.hcd"
-  EXTRA="--no2bytes --enable_lpm --tosleep=50000 "
+	if [ "$a" = "0x4330" ] ; then
+		HCD="bcm4330.hcd"
+	fi
 fi
 
 # UART TTY can be different for each board
@@ -52,6 +50,10 @@ if [ -z "$TTY" ]; then
 			break
 		fi
 	done
+fi
+
+if [ "$HCD" = "bcm4330.hcd" ]; then
+	EXTRA="--no2bytes --enable_lpm --tosleep=50000 "
 fi
 
 if [ -n "$HCD" ] ; then
