alarm/firmware-brcm43xx: Search harder for chip version
* Fixes finding chip on wandboard (mmc1) and possibly other devices
* Gracefully fail if a chip is not found.

diff --git a/alarm/firmware-brcm43xx/start-brcm-patchram-plus b/alarm/firmware-brcm43xx/start-brcm-patchram-plus
--- a/alarm/firmware-brcm43xx/start-brcm-patchram-plus
+++ b/alarm/firmware-brcm43xx/start-brcm-patchram-plus
@@ -13,7 +13,17 @@ else
 fi
 MAC_OPTIONS="--bd_addr $MAC_ADDR"
 
-a=`cat /sys/class/mmc_host/mmc0/mmc0\:0001/mmc0\:0001\:1/device`
+# Find chip version
+DEVS=($( cat /sys/class/mmc_host/mmc?/mmc?\:0001/mmc?\:0001:?/device ))
+for DEV in "${DEVS[@]}"; do
+	if [ "${DEV:0:4}" = "0x43" ]; then
+		a="$DEV"
+	fi
+done
+if [ -z "$a" ]; then
+	echo "Failed: Unable to locate bluetooth device"
+	exit 1
+fi
 
 HCD=""
 EXTRA=""
