community/xbmc to 13.1-2

diff --git a/community/xbmc/xbmc.install b/community/xbmc/xbmc.install
--- a/community/xbmc/xbmc.install
+++ b/community/xbmc/xbmc.install
@@ -10,10 +10,16 @@ post_install() {
 post_upgrade() {
   post_install $1
   if ! getent group xbmc | cut -d: -f3 | grep 420 > /dev/null 2>&1; then
-	  groupmod -g 420 xbmc
+	  groupmod -g 420 xbmc > /dev/null 2>&1
   fi
   if ! id -u xbmc | grep 420 > /dev/null 2>&1; then
-	  usermod -u 420 xbmc
+	  usermod -u 420 xbmc > /dev/null 2>&1
+	  if [[ $? -ne 0 ]]; then
+		  echo "Changing uid of user xbmc failed"
+		  echo "It is recommended that the uid is changed."
+		  echo "Stop all processes running under the xbmc user and reinstall xbmc"
+		  echo "or change the uid manually. (usermod -u 420 xbmc)"
+	  fi
 	  chown -R xbmc:xbmc /var/lib/xbmc
   fi
 }
