toolchain to gcc 4.6.1, glibc 2.14, binutils 2.21.1

diff --git a/core/glibc/PKGBUILD b/core/glibc/PKGBUILD
--- a/core/glibc/PKGBUILD
+++ b/core/glibc/PKGBUILD
@@ -1,28 +1,28 @@
-# $Id: PKGBUILD 116984 2011-03-27 06:35:25Z allan $
+# $Id: PKGBUILD 128661 2011-06-25 11:56:19Z allan $
 # Maintainer: Allan McRae <allan@archlinux.org>
 
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
 # NOTE: valgrind requires rebuilt with each new glibc version
 
 # ALARM: Kevin Mihelich <kevin@plugapps.com>
-#  - Added source file for glibc-ports-2.13, needed for building on ARM
-#  - Symlink glibc-ports-2.13 source dir to ports dir in glibc directory
-#  - Changed configure to enable ports add-on, specify our build host type
-#  - Disable distcc and ccache, make -j1
+# - Added source file for glibc-ports-2.14, needed for building on ARM
+# - Symlink glibc-ports-2.14 source dir to ports dir in glibc directory
+# - Changed configure to enable ports add-on, specify our build host type
+# - Disabled distcc and ccache, make -j1 for v5, -j2 for v7
 
 plugrel=1
 noautobuild=1
 
 pkgname=glibc
-pkgver=2.13
-pkgrel=5
-_glibcdate=20110117
+pkgver=2.14
+pkgrel=4
+_glibcdate=20110617
 pkgdesc="GNU C Library"
 arch=('i686' 'x86_64')
 url="http://www.gnu.org/software/libc"
 license=('GPL' 'LGPL')
 groups=('base')
-depends=('linux-api-headers>=2.6.37' 'tzdata')
+depends=('linux-api-headers>=2.6.39' 'tzdata')
 makedepends=('gcc>=4.4')
 backup=(etc/locale.gen
         etc/nscd.conf)
@@ -35,28 +35,36 @@ source=(ftp://ftp.archlinux.org/other/glibc/${pkgname}-${pkgver}_${_glibcdate}.t
         glibc-__i686.patch
         glibc-2.12.1-static-shared-getpagesize.patch
         glibc-2.12.2-ignore-origin-of-privileged-program.patch
-        glibc-2.13-prelink.patch
         glibc-2.13-futex.patch
+        glibc-2.14-libdl-crash.patch
+        #glibc-2.14-fix-resolver-crash-typo.patch
+        glibc-2.14-revert-4462fad3.patch
+        glibc-2.14-reexport-rpc-interface.patch
+        glibc-2.14-reinstall-nis-rpc-headers.patch
         nscd
         locale.gen.txt
         locale-gen)
-md5sums=('b7b17d9c6b5b71b5e5322e04ca63c190'
-         '094e3c9b57da605917a780ab24575187'
+md5sums=('e441d745609d93c907b72548ba646dad'
+         'ee80ed9e723a085099218f959a7e344b'
          '4dadb9203b69a3210d53514bb46f41c3'
          '0c5540efc51c0b93996c51b57a8540ae'
          '40cd342e21f71f5e49e32622b25acc52'
          'a3ac6f318d680347bb6e2805d42b73b2'
          'b042647ea7d6f22ad319e12e796bd13e'
-         '24dfab6fd244f3773523412588ecc52c'
          '7d0154b7e17ea218c9fa953599d24cc4'
+         'cea62cc6b903d222c5f26e05a3c0e0e6'
+         '46e56492cccb1c9172ed3a235cf43c6c'
+         'c5de2a946215d647c8af5432ec4b0da0'
+         '55febbb72139ac7b65757df085024b83'
          'b587ee3a70c9b3713099295609afde49'
          '07ac979b6ab5eeb778d55f041529d623'
          '476e9113489f93b348b21e144b6a8fcf')
 
+
 mksource() {
   git clone git://sourceware.org/git/glibc.git
   pushd glibc
-  git checkout -b glibc-2.13-arch origin/release/2.13/master
+  git checkout -b glibc-2.14-arch origin/release/2.14/master
   popd
   tar -cvJf glibc-${pkgver}_${_glibcdate}.tar.xz glibc/*
 }
@@ -85,12 +93,24 @@ build() {
   # http://sourceware.org/git/?p=glibc.git;a=patch;h=d14e6b09 (only fedora branch...)
   patch -Np1 -i ${srcdir}/glibc-2.12.2-ignore-origin-of-privileged-program.patch
 
-  # http://sourceware.org/bugzilla/show_bug.cgi?id=12489
-  # http://sourceware.org/git/?p=glibc.git;a=commit;h=25b3aada (only fedora branch...)
-  patch -Np1 -i ${srcdir}/glibc-2.13-prelink.patch
-
   # http://sourceware.org/bugzilla/show_bug.cgi?id=12403
   patch -Np1 -i ${srcdir}/glibc-2.13-futex.patch
+
+  # http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=675155e9 (only fedora branch...)
+  # http://sourceware.org/ml/libc-alpha/2011-06/msg00006.html
+  patch -Np1 -i ${srcdir}/glibc-2.14-libdl-crash.patch
+
+  # This fixes the main segfault but not the assert fail (FS#24615)
+  # http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=57912a71 
+  #patch -Np1 -i ${srcdir}/glibc-2.14-fix-resolver-crash-typo.patch
+  # resort to reverting the bad commit completely for the moment
+  patch -Np1 -i ${srcdir}/glibc-2.14-revert-4462fad3.patch
+
+  # re-export RPC interface until libtirpc is ready as a replacement
+  # http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=acee4873 (only fedora branch...)
+  patch -Np1 -i ${srcdir}/glibc-2.14-reexport-rpc-interface.patch
+  # http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=bdd816a3 (only fedora branch...)
+  patch -Np1 -i ${srcdir}/glibc-2.14-reinstall-nis-rpc-headers.patch
 
   install -dm755 ${pkgdir}/etc
   touch ${pkgdir}/etc/ld.so.conf
@@ -99,9 +119,14 @@ build() {
   mkdir glibc-build
   cd glibc-build
 
+  if [[ ${CARCH} = "i686" ]]; then
+    # Hack to fix NPTL issues with Xen, only required on 32bit platforms
+    export CFLAGS="${CFLAGS} -mno-tls-direct-seg-refs"
+  fi
+
   # ALARM: Specify build host types
-  [[ $CARCH == "arm" ]] && CONFIGFLAG="--host=arm-unknown-linux-gnueabi --build=arm-unknown-linux-gnueabi"
-  [[ $CARCH == "armv7h" ]] && CONFIGFLAG="--host=armv7l-unknown-linux-gnueabi --build=armv7l-unknown-linux-gnueabi"
+  [[ $CARCH == "arm" ]] && CONFIGFLAG="--host=arm-unknown-linux-gnueabi --build=arm-unknown-linux-gnueabi" && MAKEFLAG="-j1"
+  [[ $CARCH == "armv7h" ]] && CONFIGFLAG="--host=armv7l-unknown-linux-gnueabi --build=armv7l-unknown-linux-gnueabi" && MAKEFLAG="-j2"
 
   echo "slibdir=/lib" >> configparms
 
@@ -115,21 +140,21 @@ build() {
       --without-cvs --disable-profile \
       --disable-multi-arch $CONFIGFLAG
         
-  make -j1
+  make $MAKEFLAG
 }
 
 check() {
   cd ${srcdir}/glibc-build
 
   # some errors are expected - manually check log files
-  make -k check || true
+  #make -k check || true
 }
 
 package() {
   cd ${srcdir}/glibc-build
   make install_root=${pkgdir} install
 
-  rm ${pkgdir}/etc/ld.so.{cache,conf}
+  rm -f ${pkgdir}/etc/ld.so.{cache,conf}
 
   install -dm755 ${pkgdir}/etc/rc.d
   install -dm755 ${pkgdir}/usr/sbin
@@ -167,7 +192,7 @@ package() {
                         usr/bin/{gencat,getconf,getent,iconv,locale} \
                         usr/bin/{localedef,pcprofiledump,rpcgen,sprof} \
                         usr/lib/getconf/* \
-                        usr/sbin/{iconvconfig,nscd,rpcinfo}
+                        usr/sbin/{iconvconfig,nscd}
   [[ $CARCH = "i686" ]] && strip $STRIP_BINARIES usr/bin/lddlibc4
 
   strip $STRIP_STATIC usr/lib/*.a \
@@ -177,5 +202,5 @@ package() {
                       lib/libnss_{compat,dns,files,hesiod,nis,nisplus}-${pkgver}.so \
                       lib/{libdl,libm,libnsl,libresolv,librt,libutil}-${pkgver}.so \
                       lib/{libmemusage,libpcprofile,libSegFault}.so \
-                      usr/lib/{pt_chown,gconv/*.so}
+                      usr/lib/{pt_chown,{audit,gconv}/*.so}
 }
