core/glibc to 2.35-3

diff --git a/core/glibc/PKGBUILD b/core/glibc/PKGBUILD
--- a/core/glibc/PKGBUILD
+++ b/core/glibc/PKGBUILD
@@ -10,19 +10,17 @@
 #  - Specify our build host type
 #  - Disabled distcc
 #  - Strip out Arch x86 multilib
-#  - Don't --enable-static-pie, broken on ARM
 #  - Don't --enable-cet, x86 only
 
 noautobuild=1
 
 pkgname=glibc
 pkgver=2.35
-pkgrel=2
+pkgrel=3
 arch=(x86_64)
 url='https://www.gnu.org/software/libc'
 license=(GPL LGPL)
 makedepends=(git gd python)
-optdepends=('perl: for mtrace')
 options=(!strip staticlibs !lto !distcc)
 #_commit=3de512be7ea6053255afed6154db9ee31d4e557a
 #source=(git+https://sourceware.org/git/glibc.git#commit=$_commit
@@ -30,7 +28,10 @@ source=(https://ftp.gnu.org/gnu/glibc/glibc-$pkgver.tar.xz{,.sig}
         locale.gen.txt
         locale-gen
         sdt.h sdt-config.h
-        disable-clone3.diff)
+        disable-clone3.diff
+        0001-localedef-Update-LC_MONETARY-handling-Bug-28845.patch
+        0001-localedata-Do-not-generate-output-if-warnings-were-p.patch
+)
 validpgpkeys=(7273542B39962DF7B299931416792B4EA25340F8 # Carlos O'Donell
               BC7C7372637EC10C57D7AA6579C43DFBF1CF2187) # Siddhesh Poyarekar
 b2sums=('623c728884f070cd87ffeb9203f74206197c52405ac9bc44f3dd519a3468b8e8ae2536c883e5d17d94417dbd1e91775de2e674314e4ff7424f9720026d6b7063'
@@ -39,7 +40,9 @@ b2sums=('623c728884f070cd87ffeb9203f74206197c52405ac9bc44f3dd519a3468b8e8ae2536c
         '1f6d927b4972220b1c00abee5329c5d6bc01ed5bee57b20db0c7d7433292f7d666b02baf9968267f8e378b1f3bb273e8eef0ccbf22d21400ac36949d7615a474'
         'a6a5e2f2a627cc0d13d11a82458cfd0aa75ec1c5a3c7647e5d5a3bb1d4c0770887a3909bfda1236803d5bc9801bfd6251e13483e9adf797e4725332cd0d91a0e'
         '214e995e84b342fe7b2a7704ce011b7c7fc74c2971f98eeb3b4e677b99c860addc0a7d91b8dc0f0b8be7537782ee331999e02ba48f4ccc1c331b60f27d715678'
-        'edef5f724f68ea95c6b0127bd13a10245f548afc381b2d0a6d1d06ee9f87b7dd89c6becd35d5ae722bf838594eb870a747f67f07f46e7d63f8c8d1a43cce4a52')
+        'edef5f724f68ea95c6b0127bd13a10245f548afc381b2d0a6d1d06ee9f87b7dd89c6becd35d5ae722bf838594eb870a747f67f07f46e7d63f8c8d1a43cce4a52'
+        '3c4de02d6308a4d39693e6effa08894ae096397347e439b93b0b5328aba41a373f7f2eeb88c109970f69cca65aaa74ba14e384d6d033f6a913438f4f920854a6'
+        'b6014af23688ea971d7af38d58829c8016a0af63770b7f5e8bc986c13ea2cafefe0935ff483b1b37c87ebe3e652b6e0c48ab43dd8ae752d0ed7fecc3751432f4')
 
 prepare() {
   mkdir -p glibc-build
@@ -53,6 +56,10 @@ prepare() {
   # Patch src: https://patchwork.ozlabs.org/project/glibc/patch/87eebkf8ph.fsf@oldenburg.str.redhat.com/
   patch -Np1 -i "${srcdir}"/disable-clone3.diff
 
+  # Fix C.UTF-8 generation errors
+  # https://bugs.archlinux.org/task/73797
+  patch -Np1 -i "${srcdir}"/0001-localedef-Update-LC_MONETARY-handling-Bug-28845.patch
+  patch -Np1 -i "${srcdir}"/0001-localedata-Do-not-generate-output-if-warnings-were-p.patch
 }
 
 build() {
@@ -60,12 +67,9 @@ build() {
       --prefix=/usr
       --with-headers=/usr/include
       --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues
-      --enable-add-ons
       --enable-bind-now
-      --enable-lock-elision
       --disable-multi-arch
       --enable-stack-protector=strong
-      --enable-stackguard-randomization
       --enable-systemtap
       --disable-profile
       --disable-crypt
@@ -103,7 +107,7 @@ build() {
   echo "CFLAGS += -Wp,-D_FORTIFY_SOURCE=2" >> configparms
   make -O
 
-  # build info pages manually for reprducibility
+  # build info pages manually for reproducibility
   make info
 }
 
@@ -127,7 +131,7 @@ check() {
 
   # The following tests fail due to restrictions in the Arch build system
   # The correct fix is to add the following to the systemd-nspawn call:
-  # --capability=CAP_IPC_LOCK --system-call-filter="@clock @pkey"
+  # --system-call-filter="@clock @memlock @pkey"
   skip_test test-errno-linux sysdeps/unix/sysv/linux/Makefile
   skip_test tst-ntp_gettime  sysdeps/unix/sysv/linux/Makefile
   skip_test tst-ntp_gettimex sysdeps/unix/sysv/linux/Makefile
@@ -142,17 +146,15 @@ check() {
 package() {
   pkgdesc='GNU C Library'
   depends=('linux-api-headers>=4.10' tzdata filesystem)
-  optdepends=('gd: for memusagestat')
+  optdepends=('gd: for memusagestat'
+              'perl: for mtrace')
   install=glibc.install
   backup=(etc/gai.conf
           etc/locale.gen
           etc/nscd.conf)
 
-  install -dm755 "$pkgdir/etc"
-  touch "$pkgdir/etc/ld.so.conf"
-
   make -C glibc-build install_root="$pkgdir" install
-  rm -f "$pkgdir"/etc/ld.so.{cache,conf}
+  rm -f "$pkgdir"/etc/ld.so.cache
 
   # Shipped in tzdata
   rm -f "$pkgdir"/usr/bin/{tzselect,zdump,zic}
@@ -180,18 +182,15 @@ package() {
 
     # Do not strip these for gdb and valgrind functionality, but strip the rest
     find "$pkgdir"/usr/lib \
-      -not -name 'ld-*.so' \
-      -not -name 'libc-*.so' \
-      -not -name 'libpthread-*.so' \
-      -not -name 'libthread_db-*.so' \
-      -name '*-*.so' -type f -exec strip $STRIP_SHARED {} + 2> /dev/null || true
+      -not -name 'ld-*.so*' \
+      -not -name 'libc.so*' \
+      -not -name 'libpthread.so*' \
+      -not -name 'libthread_db.so*' \
+      -name '*.so*' -type f -exec strip $STRIP_SHARED {} + 2> /dev/null || true
   fi
 
   # Provide tracing probes to libstdc++ for exceptions, possibly for other
   # libraries too. Useful for gdb's catch command.
   install -Dm644 "$srcdir/sdt.h" "$pkgdir/usr/include/sys/sdt.h"
   install -Dm644 "$srcdir/sdt-config.h" "$pkgdir/usr/include/sys/sdt-config.h"
-
-  # Provided by libxcrypt; keep the old shared library for backwards compatibility
-  rm -f "$pkgdir"/usr/include/crypt.h "$pkgdir"/usr/lib/libcrypt.{a,so}
 }
