core/systemd to 253.3-3

diff --git a/core/systemd/systemd-hook b/core/systemd/systemd-hook
--- a/core/systemd/systemd-hook
+++ b/core/systemd/systemd-hook
@@ -26,21 +26,51 @@ udevd_live() {
 op="$1"; shift
 
 case "$op" in
-  catalog)  /usr/bin/journalctl --update-catalog ;;
-  hwdb)     /usr/bin/systemd-hwdb --usr update ;;
-  update)   touch -c /usr ;;
-  sysusers) /usr/bin/systemd-sysusers ;;
-  tmpfiles) /usr/bin/systemd-tmpfiles --create ;;
+  catalog)
+    /usr/bin/journalctl --update-catalog
+    ;;
+  hwdb)
+    /usr/bin/systemd-hwdb --usr update
+    ;;
+  update)
+    touch -c /usr
+    ;;
+  sysusers)
+    /usr/bin/systemd-sysusers
+    ;;
+  tmpfiles)
+    /usr/bin/systemd-tmpfiles --create
+    ;;
 
-  daemon-reload) systemd_live; /usr/bin/systemctl daemon-reload ;;
-  udev-reload)   udevd_live;   /usr/bin/udevadm control --reload; /usr/bin/udevadm trigger ;;
-  binfmt)        systemd_live; /usr/lib/systemd/systemd-binfmt ;;
-  sysctl)        systemd_live; /usr/lib/systemd/systemd-sysctl ;;
+  daemon-reload)
+    systemd_live
+    /usr/bin/systemctl daemon-reload
+    ;;
+  udev-reload)
+    udevd_live
+    /usr/bin/udevadm control --reload
+    /usr/bin/udevadm trigger
+    /usr/bin/udevadm settle
+    ;;
+  binfmt)
+    systemd_live
+    /usr/lib/systemd/systemd-binfmt
+    ;;
+  sysctl)
+    systemd_live
+    /usr/lib/systemd/systemd-sysctl
+    ;;
 
   # For use by other packages
-  reload)        systemd_live; /usr/bin/systemctl try-reload-or-restart "$@" ;;
+  reload)
+    systemd_live
+    /usr/bin/systemctl try-reload-or-restart "$@"
+    ;;
 
-  *) echo >&2 "  Invalid operation '$op'"; exit 1 ;;
+  *)
+    echo >&2 "  Invalid operation '$op'"
+    exit 1
+    ;;
 esac
 
 exit 0
