aur/plexmediaserver to 0.9.8.10.215

diff --git a/aur/plexmediaserver/start_pms b/aur/plexmediaserver/start_pms
--- a/aur/plexmediaserver/start_pms
+++ b/aur/plexmediaserver/start_pms
@@ -10,6 +10,17 @@ export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="${PLEX_MEDIA_SERVER_HOME}/Libr
 
 test -f /etc/conf.d/plexmediaserver && . /etc/conf.d/plexmediaserver
 
+#if [ -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ]
+#then
+#  chown -R ${PLEX_MEDIA_SERVER_USER} "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
+#  if [ ! $? -eq 0 ]
+#  then
+#    echo "WARNING COULDN'T CHOWN $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR files to ${PLEX_MEDIA_SERVER_USER}, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+#    exit 1
+#  fi
+#fi
+
+
 if [ ! -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ]
 then
   mkdir -p "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
