extra/valgrind to 3.15.0+269+gd772e2599-1

diff --git a/extra/valgrind/PKGBUILD b/extra/valgrind/PKGBUILD
--- a/extra/valgrind/PKGBUILD
+++ b/extra/valgrind/PKGBUILD
@@ -11,8 +11,8 @@ buildarch=12
 noautobuild=1
 
 pkgname=valgrind
-_commit=608cb11914e5f23d0fc12c61dad29c5c7952a1de  # tags/VALGRIND_3_15_0^0
-pkgver=3.15.0
+_commit=d772e25995c3400eecf2b6070e0bf3411447c3d1
+pkgver=3.15.0+269+gd772e2599
 pkgrel=1
 pkgdesc='Tool to help find memory-management problems in programs'
 arch=('x86_64')
@@ -76,32 +76,32 @@ check() {
   # sets all flags necessary. See also configure above.
   make check CPPFLAGS= CFLAGS= CXXFLAGS= LDFLAGS=
 
-  # XXX: run full regtest but only report issues some tests fail duo
-  # current toolchain and expectations, take a manual look if its fine
-  echo "===============TESTING==================="
-  make regtest || :
+  # # XXX: run full regtest but only report issues some tests fail duo
+  # # current toolchain and expectations, take a manual look if its fine
+  # echo "===============TESTING==================="
+  # make regtest || :
 
-  # Make sure test failures show up in build.log
-  # Gather up the diffs (at most the first 20 lines for each one)
-  local f max_lines=20 diff_files=()
-  mapfile -d '' diff_files < <(find . -name '*.diff' -print0 | sort -z)
-  if (( ${#diff_files[@]} == 0 )); then
-    echo "Congratulations, all tests passed!"
-  else
-    warning "Some tests failed!"
-    for f in "${diff_files[@]}"; do
-        echo "================================================="
-        echo "${f}"
-        echo "================================================="
-        if (( $(wc -l < "${f}") < ${max_lines} )); then
-          cat "${f}"
-        else
-          head -n ${max_lines} "${f}"
-          echo "<truncated beyond ${max_lines} lines>"
-        fi
-    done | tee diffs
-  fi
-  echo "===============END TESTING==============="
+  # # Make sure test failures show up in build.log
+  # # Gather up the diffs (at most the first 20 lines for each one)
+  # local f max_lines=20 diff_files=()
+  # mapfile -d '' diff_files < <(find . -name '*.diff' -print0 | sort -z)
+  # if (( ${#diff_files[@]} == 0 )); then
+  #   echo "Congratulations, all tests passed!"
+  # else
+  #   warning "Some tests failed!"
+  #   for f in "${diff_files[@]}"; do
+  #       echo "================================================="
+  #       echo "${f}"
+  #       echo "================================================="
+  #       if (( $(wc -l < "${f}") < ${max_lines} )); then
+  #         cat "${f}"
+  #       else
+  #         head -n ${max_lines} "${f}"
+  #         echo "<truncated beyond ${max_lines} lines>"
+  #       fi
+  #   done | tee diffs
+  # fi
+  # echo "===============END TESTING==============="
 }
 
 package() {
